name: Build & Release

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "MCServerUpdater"
          path: "./mc-server-updater-standalone/target/MCServerUpdater.jar"
      - name: "Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./mc-server-updater-standalone/target/MCServerUpdater.jar
            ./mc-server-updater-lib/target/mc-server-updater-lib-*.jar
